
language: ruby

rvm:
  - 2.0.0

before_install:
  - gem --version
  - git clone https://github.com/bernd/fpm-cookery.git

script:
  - bundle exec fpm-cook --version
  - sudo env PATH=$PATH bundle exec fpm-cook package odpscmd/recipe.rb
