
before_script:
  - curl -s http://repo.aliyun.com/deb.gpg.key | sudo apt-key add -
  - echo "deb http://repo.aliyun.com/apt/debian/ /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install odpscmd

script:
  - odpscmd --version

