site_name: 阿里云 ODPS 生态
site_favicon: favicon.ico
theme: bootstrap
google_analytics: ['UA-70496103-1', 'repo.aliyun.com']
pages:
- Home: 'index.md'
- Console: 'odpscmd.md'
- ETL Console: 'etl.md'
- ETL SDK: 'etl-sdk.md'
- JDBC: 'jdbc.md'
- Fluentd: 'fluentd.md'
- Logstash: 'logstash.md'
- Flume: 'flume.md'
