site_name: Aliyun MaxCompute Ecosystem
site_favicon: favicon.ico
theme: bootstrap
google_analytics: ['UA-70496103-1', 'repo.aliyun.com']
pages:
- Home: 'index.md'
- CLI tool: 'odpscmd.md'
- Opensource tools link: 'opensource.md'
